version: '3.8'

services:
  polkadot-node:
    container_name: kusama-overview-kusama-node
    image: parity/polkadot:latest
    user: root
    volumes:
      - '.chain-data:/root/.local/share/polkadot'
    command: --chain kusama --pruning archive --wasm-execution Compiled --db paritydb --unsafe-ws-external --rpc-cors all
  mongo:
    container_name: kusama-overview-mongo
    image: mongo
    user: root
    volumes:
      - '.mongo-data:/data/db'
  kusama-overview-app:
    container_name: kusama-overview-app
    image: kusama-overview-app:production
    build:
      context: .
      args:
        ENVIRONMENT: 'production'
    volumes:
      - .:/usr/src/kusama-overview
      - /usr/src/kusama-overview/node_modules
      - /usr/src/kusama-overview/api/node_modules
      - /usr/src/kusama-overview/parser-light/node_modules
      - /usr/src/kusama-overview/ui/node_modules
    ports:
      - "3002:3002"
      - "4002:4002"
